### ISSUE TITLE
Install / Usage instructions not working

### ISSUE THREAD

**Issue by taylor-schneider** [rgerganov/shanocast#5]
I installed Nix using the command provided, but then I cannot run the receiver

```
retro@retropie:~$ nix run .#shanocast wlxbcec23cab2d2
path '/home/retro' does not contain a 'flake.nix', searching up
error: could not find a flake.nix file
```

Is there a missing step?

**Comment by alequint8912** [comment]
Hello. I realize that that command needs to be run inside the shanocast folder (after cloning). But I still have problems with the openscreen part.

Maybe there is a guide for non-advanced Linux users?

**Comment by alequint8912** [comment]
Got this error

~/.../shanocast$ nix run .
warning: Ignoring setting 'auto-allocate-uids' because experimental feature 'auto-allocate-uids' is not enabled
warning: Ignoring setting 'impure-env' because experimental feature 'configurable-impure-env' is not enabled
[INFO:../../cast/receiver/channel/static_credentials.cc(272):T0] Generated new private key for session: ./generated_root_cast_receiver.key
[INFO:../../cast/receiver/channel/static_credentials.cc(280):T0] Generated new root certificate for session: ./generated_root_cast_receiver.crt
[FATAL:../../cast/standalone_receiver/main.cc(208):T0] OSP_CHECK(interface_name && strlen(interface_name) > 0) failed: No interface name provided.
Abortado (`core' generado)

**Comment by taylor-schneider** [comment]
When I did a git clone, cd'd into the directory, and then ran I saw the following:
```
retro@retropie:~/shanocast$ nix run .#shanocast wlxbcec23cab2d2
[1/0/1 copied (108.8/146.5 MiB), 17.2/23.8 MiB DL] fetching source from https://cache.nixos.org
[1/0/1 copied (108.8/146.5 MiB), 17.2/23.8 MiB DL] fetching source from https://cache.nixos.org

error: RPC failed; curl 92 HTTP/2 stream 7 was not closed cleanly: CANCEL (err 8)
error: 6732 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
fatal: Fetched in submodule path 'third_party/valijson/src/thirdparty/nlohmann-json', but it did not contain 183390c10b8ba4aa33934ae593f82f352befefc8. Direct fetching of that commit failed.
fatal: Failed to recurse into submodule path 'third_party/valijson/src'
error:
       … while calling the 'derivationStrict' builtin

         at /derivation-internal.nix:9:12:

            8|
            9|   strict = derivationStrict drvAttrs;
             |            ^
           10|

       … while evaluating derivation 'shanocast'
         whose name attribute is located at /nix/store/55ql4j8d47xjvfa8xggjddgfwny4n9j7-source/pkgs/stdenv/generic/make-derivation.nix:348:7

       … while evaluating attribute 'src' of derivation 'shanocast'

         at /nix/store/8jqrhnx48lyl19mv4asz1ysz2z42xnjw-source/cast_receiver.nix:14:10:

           13|   name = "shanocast";
           14|   inherit src;
             |          ^
           15|   NIX_CFLAGS_COMPILE =

       error: program 'git' failed with exit code 128
```

I then rm -rf the directory, and cloned recursively

I tried rerunning the command but it just seemed to hang there... the --log-format raw lag did not help either

**Comment by taylor-schneider** [comment]
> Got this error
> 
> ~/.../shanocast$ nix run . warning: Ignoring setting 'auto-allocate-uids' because experimental feature 'auto-allocate-uids' is not enabled warning: Ignoring setting 'impure-env' because experimental feature 'configurable-impure-env' is not enabled [INFO:../../cast/receiver/channel/static_credentials.cc(272):T0] Generated new private key for session: ./generated_root_cast_receiver.key [INFO:../../cast/receiver/channel/static_credentials.cc(280):T0] Generated new root certificate for session: ./generated_root_cast_receiver.crt [FATAL:../../cast/standalone_receiver/main.cc(208):T0] OSP_CHECK(interface_name && strlen(interface_name) > 0) failed: No interface name provided. Abortado (`core' generado)

It looks like you got farther than I did. Your command is missing the name of the interface you want to run the service on. Can you tell me what OS, os version, and nix version you are using?

**Comment by taylor-schneider** [comment]
@alequint8912 any update?

**Comment by taylor-schneider** [comment]
@rgerganov  any thoughts?

**Comment by MatthewCroughan** [comment]
@taylor-schneider for some reason, the inputs (source code) changed from the expected value stored in the lock file. This can happen for tons of reasons, such as Google force pushing, rebasing, or overwriting history, I'm not sure what caused this yet, but I'll keep an eye on it.

Should be fixed in https://github.com/rgerganov/shanocast/pull/6

Based on your logs though, I think you also have some network issues unrelated to Nix, or this repo. See the http transport errors. The fact that you're doing this on a Pi which may have a weak WiFi signal aren't helping this.

Additionally, if you want to use this program you're going to need to run an avahi daemon configured to allow user services.

Don't get your hopes up, by the way. In my experience playing around with this, the stream eventually cuts out, and is not stable. Not sure why.

If you want to try out my fix before @rgerganov merges it, then just

`nix run github:matthewcroughan/shanocast <interface_name>`

**Comment by HuntCode** [comment]
> 
> In my experience playing around with this, the stream eventually cuts out, and is not stable. Not sure why.
> 
@MatthewCroughan do you have the same problem like #11 ? I don't know the reason either

**Comment by andycylam** [comment]
@MatthewCroughan I also get this error

`error:
       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:34:12:
           33|
           34|   strict = derivationStrict drvAttrs;
             |            ^
           35|

       … while evaluating derivation 'shanocast'
         whose name attribute is located at /nix/store/55ql4j8d47xjvfa8xggjddgfwny4n9j7-source/pkgs/stdenv/generic/make-derivation.nix:348:7

       … while evaluating attribute 'src' of derivation 'shanocast'
         at /nix/store/clxxzvl9x0s39fa2vbhv6psmn17pjdgv-source/cast_receiver.nix:14:11:
           13|   name = "shanocast";
           14|   inherit src;
             |           ^
           15|   NIX_CFLAGS_COMPILE =

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: mismatch in field 'narHash' of input '{"__final":true,"lastModified":1695839408,"narHash":"sha256-qzE/JIgpXmLsW6AiIOs1pU8eQpbyTZ1Kw5DPYqvzAYM=","ref":"refs/heads/main","rev":"934f2462ad01c407a596641dbc611df49e2017b4","revCount":1184,"shallow":true,"submodules":true,"type":"git","url":"https://chromium.googlesource.com/openscreen.git"}', got '{"__final":true,"lastModified":1695839408,"narHash":"sha256-Sf9mctuhcO5rXC82xkemr1/2Il5lJYX9x21vTZjngAw=","ref":"refs/heads/main","rev":"934f2462ad01c407a596641dbc611df49e2017b4","revCount":1184,"shallow":true,"submodules":true,"type":"git","url":"https://chromium.googlesource.com/openscreen.git"}'
`

**Comment by HuntCode** [comment]
@andycylam you can change the narHash and try again, as https://github.com/rgerganov/shanocast/pull/6#issuecomment-2547377917 did
